spring.cloud.stream.bindings.output.contentType: text/plain
spring.application.name: kafka-streams-aggregate-sample
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

#spring.cloud.stream.bindings.applicationMetrics.destination: metrics
#spring.cloud.stream.bindings.applicationMetrics.binder.brokers: ec2-35-174-17-30.compute-1.amazonaws.com:9092

spring.cloud.stream.kafka.streams.binder.configuration.application.id: default
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.serdeError: sendToDlq
spring.cloud.stream.kafka.streams.bindings.input.consumer.enableDlq: true
spring.cloud.stream.kafka.streams.bindings.input.consumer.dlqName: order-errors
spring.cloud.stream.kafka.streams.bindings.input.consumer.useNativeDecoding: false
spring.cloud.stream.kafka.streams.bindings.input.group: orderGroup

spring.cloud.stream.kafka.streams.bindings.input.destination.group: groupLocal
spring.cloud.stream.kafka.streams.bindings.input.consumer.startOffset: latest
spring.kafka.consumer.group-id: groupLocal
spring.kafka.consumer.auto-offset-reset: latest

spring.cloud.dataflow.stream.name: pivotMartOrders
spring.cloud.stream.bindings.output.destination: pivotMartOrders.orders
spring.cloud.stream.kafka.streams.binder.brokers: ec2-35-174-17-30.compute-1.amazonaws.com:9092
spring.cloud.stream.kafka.binder.brokers: ec2-35-174-17-30.compute-1.amazonaws.com:9092
spring.cloud.stream.kafka.binder.zkNodes: ec2-35-174-17-30.compute-1.amazonaws.com:2181


spring.cloud.stream.bindings.input.destination: pivotMartOrders.http
spring.cloud.stream.bindings.input.group: groupLocal
spring.cloud.stream.bindings.input.consumer.useNativeDecoding: false
spring.cloud.stream.kafka.bindings.input.consumer.enableDlq: true
spring.cloud.stream.kafka.bindings.input.consumer.dlqName: pivotMartOrders.errors


spring.cloud.stream.bindings.error.destination: myErrors

server.port: 7088
  